version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: nlw-server
    ports:
      - ${PORT}:${PORT}
      - "5555:5555"
    volumes:
      - .:/home/node/app
